import { test, expect } from '@playwright/test';

test('Asignar roles', async ({ page }) => {
  await page.goto('http://localhost:3001/');
  await page.getByRole('button', { name: 'Añadir Nueva Excursión...' }).click();
  await page.getByRole('textbox', { name: 'Nombre de la Excursión' }).click();
  await page.getByRole('textbox', { name: 'Nombre de la Excursión' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre de la Excursión' }).fill('T');
  await page.getByRole('textbox', { name: 'Nombre de la Excursión' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre de la Excursión' }).fill('Teatro');
  await page.getByRole('spinbutton', { name: 'Número de Alumnos' }).click();
  await page.getByRole('spinbutton', { name: 'Número de Alumnos' }).fill('40');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('B');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Belen ');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Belen C');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Belen Chijo');
  await page.getByRole('combobox', { name: 'Rol' }).click();
  await page.getByRole('option', { name: 'Profesora' }).click();
  await page.getByRole('button', { name: 'Agregar Adulto' }).click();
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('M');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Mariela ');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Mariela F');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Mariela Fuentes');
  await page.getByRole('combobox', { name: 'Rol' }).click();
  await page.getByRole('option', { name: 'Coordinadora' }).click();
  await page.getByRole('button', { name: 'Agregar Adulto' }).click();
  await page.getByRole('textbox', { name: 'Fecha' }).click();
  await page.getByRole('textbox', { name: 'Fecha' }).fill('20/07');
  await page.getByRole('textbox', { name: 'Horario' }).click();
  await page.getByRole('textbox', { name: 'Horario' }).fill('11:00');
  await page.getByRole('button', { name: 'Agregar Excursión' }).click();
  await expect(page.locator("body")).toContainText("Teatro");
  await expect(page.locator("body")).toContainText("Teatro");
});